context:
  version: "18.0.0"

package:
  name: nyc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/nyc/-/nyc-${{ version }}.tgz
  sha256: 4a6907ef0956103a192bd29e1a784524f3ed8f1832eec438eee937c4828577be

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nyc --help 2>&1 | grep -q "nyc.js \[command\] \[options\]"

about:
  license: ISC
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: the Istanbul command line interface
  homepage: https://github.com/istanbuljs/nyc
  repository: https://github.com/istanbuljs/nyc

extra:
  recipe-maintainers:
    - danielnachun
